#!/bin/bash

SCRIPT_DIRECTORY="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

source $SCRIPT_DIRECTORY/common

set -o pipefail
set -u

help() {
    echo "help: ${0} -e <environment> -a <action> [<args>]"
    exit 1
}

check_terraform
check_version
verify_no_credentials_set

# Validate invocation
regex="^-e ([0-9a-zA-Z-]*) -a ([a-zA-Z]*)([ a-zA-Z]*)\$"
if [[ ! $* =~ $regex ]]; then
    help
fi

# Need to parse all args first
while [[ $# -gt 0 ]]; do
    key="$1"
    case $key in
    -e | --environment)
        validate_profile
        validate_environment $2
        environment="$2"
        shift
        ;;
    -a | --action)
        validate_action $2
        action="$2"
        action_args="${@:3}"
        break
        ;;
    *)
        echo "Set failed: unknown option $1"
        echo
        help
        exit 1
        ;;
    esac
    shift
done

warn_proxy

load_profile_configuration

WORKSPACE_KEY_PREFIX=psc-discrepancy-parser
WORKSPACE=$environment
STATEFILE_NAME=psc-discrepancy-parser.tfstate

check_proceed

banner "-"

initialise_terraform

if var_file_action $action; then
    vars_file_flag="-var-file=$vars_file"
else
    vars_file_flag=
fi

command="terraform $action $action_args $vars_file_flag"
printf "${BOLD}$command${NORMAL}\n"
eval $command

banner "-"
