variable psc_discrepancy_bucket {}
variable handler {}
variable memory_megabytes {}
variable release_bucket_name {}
variable runtime {}
variable timeout_seconds {}
variable project_name {}
variable release_version {}
variable execution_role {}
variable subnet_ids {}
variable security_group_ids {}
variable s3_bucket_kms_arn {}